### ISSUE TITLE
Request: LMG Gun

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [zaeonNineZero/NineZero-Gun-Expansion#1]
It Would Be Nice If There Was A Light Machine Gun In This Mod.

**Comment by chemlzh** [comment]
Seems that LMG has been on the roadmap.

**Comment by zaeonNineZero** [comment]
> It Would Be Nice If There Was A Light Machine Gun In This Mod.

It would be nice, wouldn't it!

An LMG (the 'Machine Gun') will be part of the 1.2.0 release, which is set to be released in the coming days. Feel free to post any more suggestions you may have.
