### ISSUE TITLE
[Suggestion] Add silenced assault rifle based on AS VAL

### ISSUE THREAD

**Issue by chemlzh** [zaeonNineZero/NineZero-Gun-Expansion#12]
Now CGM and NZGE have not dealt with the problem that short-to-mid-range rifle dealt less damage when silencer is installed, and long-range rifle cannot fire automatically or not suitable for CQB. Therefore a silenced assault rifle with integrated silencer(suppressor) can be made to fill the niche.

The new rifle fire medium bullets, can use 20-round original magazine or 30-round SR-3M magazine (depends on balance), with scope, stock and foregrip integration choice (See picture below). Since AS VAL use 9x39 mm subsonic rounds, the blast is small, and you can only hear fire sounds at a close distance. As an exchange, the bullet velocity of the game counterpart is slower than heavy assalt rifle, and therefore the bullets will drop at a long range.

The damage can be set between assalt rifle and heavy assalt rifle for balance (since 9x39 mm rounds has 650-850 Joule muzzle energy), which means it takes three rounds to beat down a player with 20 life points.

![Full upgraded AS VAL in Escape From Tarkov](https://github.com/zaeonNineZero/NineZero-Gun-Expansion/assets/32123043/52f2f2d9-cc88-470f-a384-0b14bcbbe824)

**Note:** Do you think adding rifles like ASh-12.7/ShAK-12.7 will be fun? (Just a joke, I don't think a large-calibre battle rifle with great recoil will be loved.)

![ASh-12_Bullpup_assault_rifle](https://github.com/zaeonNineZero/NineZero-Gun-Expansion/assets/32123043/3562f140-8316-4856-9774-6aa29c2042a0)

**Comment by zaeonNineZero** [comment]
I think this addition may be too out of scope for NZGE, but I will add this onto the roadmap as an 'in consideration' item in case I want to revisit it in the future.
