### ISSUE TITLE
[Bug] Possible bug with datapack

### ISSUE THREAD

**Issue by Avventis90005** [zaeonNineZero/NineZero-Gun-Expansion#15]
Good time of day.
To begin with, I would like to apologize for my not the best knowledge of english, but I will still try to explain everything in a way that is clear.
There was a need to change some parameters of the weapon so that it would correspond to the current modpack.
In the Crayfish Gun Mod there was a possibility to change weapons stats through a datapack and it worked.
I assumed that it should work with nzgmaddon through the same way, but I was faced with the fact that the data from the datapack does not affect anything.
The datapack itself is located at: datapacks\<datapack_name>\data\nzgmaddon\guns\. 
Inside this datapack there is already a segment for CGM, which works (and that means, that datapack is read by minecraft).
There is also a part for nzgmaddon. And it doesn't work. Perhaps I'm doing something wrong?

If everything works the same as in CGM, it means that the datapack is unreadable for some reason? Perhaps there is a mistake in the location address or something else? Is it bug?
![image](https://github.com/zaeonNineZero/NineZero-Gun-Expansion/assets/42994109/9dfebeda-58cb-4ca3-b07f-19f91c5da474)

I'm using minecraft 1.19.2 and this version of nzgmaddon: nzgExpansion-1.3.1-1.19.2
Forge 43.2.13

**Comment by zaeonNineZero** [comment]
The datapack location and folder structure look fine to me, as does the sniper_rifle.json file. This might be a datapack priority issue. Basically, if a datapack is added before another mod is installed, the mod's own data will load after the datapack and take higher priority. Disabling and re-enabling the datapack again usually fixes this, as it moves the datapack back to the bottom of the load order. (Hence, it loads last)

Let me know if this helped any!

**Comment by Avventis90005** [comment]
The /Reload command had no effect. The datapack still does not work. 
If it is important, I took the JSON files for the datapack from here: 
![image](https://github.com/zaeonNineZero/NineZero-Gun-Expansion/assets/42994109/ac4ab12a-b472-4667-a5cc-e448ac5a65f6)

**Comment by zaeonNineZero** [comment]
1. You need to run `/datapack disable <name>`, followed by `/datapack enable <name>` to move the datapack to the bottom of the load order. Try running those and see if anything changes.
2. Those are the correct .json files, so you're good on that end.

**Comment by Avventis90005** [comment]
Finally XD
That's worked. Thanks you very much. 
![image](https://github.com/zaeonNineZero/NineZero-Gun-Expansion/assets/42994109/06a8efa3-8f82-4c09-868a-da44cb7ed8aa)

Maybe it would be advisable to place some information somewhere on what needs to be done for the datapack to work, to make it easier to find the information if someone else has the same question?

**Comment by zaeonNineZero** [comment]
I'll think about where to place that information. Maybe I'll make a pinned issue (a closed one that is) detailing what to do.

Anyway, glad I could be of help!
