### ISSUE TITLE
[Suggestion] Update Simplified Chinese Language Pack And CGM AVE Port on 1.18.2

### ISSUE THREAD

**Issue by chemlzh** [zaeonNineZero/NineZero-Gun-Expansion#2]
### Description

I have made a Simplified Chinese pack for NZGE, as well as an unofficial CGM Audio/Visual Enhancements port to MC 1.18.2. Could you please check for a while and update them?

NZGE Simplified Chinese pack: https://github.com/chemlzh/Ngzexpansion_language_pack_CHS_1.18.2

CGM AVE unofficial port: https://github.com/chemlzh/CGM_AVE_unofficial_1.18.2

**Comment by zaeonNineZero** [comment]
Both look good to me so far! I'll do a bit of testing with them and make them official once I validate them.

Thanks for the suggestion and submission!

**Comment by zaeonNineZero** [comment]
I have implemented the Simplified Chinese translation into NZGE for 1.18.2 through 1.19.3 and it will be included in the 1.2.0 update.

I also tested and validated the 1.18.2 CGM AVE port you made, and added in the changes I've made for the 1.1.0 version of the pack. I appreciate your work in making the 1.18.2 port, so thank you so much!

As a formality, do I have permission to use the translations and CGM AVE port you provided in both NZGE and the official version of CGM AVE?

**Comment by chemlzh** [comment]
Yes, you can use the translations and CGM AVE port. All you need to do is to cite/mention the contributor. I'm very pleased to see my datapack/resourcepack being used. In addition, I'll update my personal simplified Chinese translation once you release the newer version of NZGE and CGM AVE.

**Comment by zaeonNineZero** [comment]
Thank you! I have included the translations in the current NZGE 1.2.0 updates released today. The updates to CGM AVE will be coming shortly as well. Again, thank you for your contributions!
