### ISSUE TITLE
Medium Scope Model Inconsistency

### ISSUE THREAD

**Issue by TheLovingRockerboy** [zaeonNineZero/NineZero-Gun-Expansion#24]
![image_2024-04-25_221112102](https://github.com/zaeonNineZero/NineZero-Gun-Expansion/assets/168152637/b643e9c4-c2b9-442c-9f91-ecf2d0302a41)

![Screenshot 2024-04-25 221005](https://github.com/zaeonNineZero/NineZero-Gun-Expansion/assets/168152637/16b0faee-1ad9-4839-bae2-43a44520ae9d)

There's an issue with the Medium Scope not displaying it's model properly in-game

Image 1 Displays what it is advertised to look like

Image 2 displays what it looks like in-game (note the Short and Long Scopes in my inventory, which have already had their models swapped.)

**Comment by zaeonNineZero** [comment]
My bad - this is an oversight from CGM-A/VE's v1.2 update. That model is now part of NZGE as the 'Chevron Scope', and the Medium Scope now uses its original model with a modified reticle. I will replace that image with one that properly reflects the actual changes.

**Comment by zaeonNineZero** [comment]
Fixed the description on the CurseForge page. It should be rolling out shortly.
