### ISSUE TITLE
Bug with ballistic scope and embeddium

### ISSUE THREAD

**Issue by An0m3L1** [zaeonNineZero/NineZero-Gun-Expansion#25]
For some reason, the emissive dot in the ballistic scope stretches out on the x-axis when both embeddium and nzge are present.
![javaw_EhmCR8ZVwY](https://github.com/zaeonNineZero/NineZero-Gun-Expansion/assets/93768372/5a8198b8-ba9e-4f1f-a4cf-bf28df80b764) Shaders don't influence the bug.

**Comment by zaeonNineZero** [comment]
Context for others who have encountered this issue: the emissive dot model element seems to be getting stretched along the x-axis, likely by Embeddium's rendering code. This is not a UV/texture and does not occur when Rubidium (or neither Sodium port) is installed.

For An0m: Can you also post a screenshot showing the scope's reticle without Embeddium installed? And can you share which MC and Forge version this occurred on? Thanks in advance!

**Comment by zaeonNineZero** [comment]
The Embeddium team figured out what was causing the bug and fixed it in their beta branch. The fix will be pushed out with the next release of Embeddium. I'll keep this issue open until then.

**Comment by zaeonNineZero** [comment]
Should be resolved in Embeddium 0.3.18.
