### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by davethemodderguy** [zaeonNineZero/NineZero-Gun-Expansion#28]
Update to 1.20.1 use the unofficial version here:
https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod-unofficial

**Comment by LessThanCasual** [comment]
read the q&a

**Comment by zaeonNineZero** [comment]
Closing as not planned -- I have no plans to support unofficial ports of CGM
