### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by wxjk-1** [zaeonNineZero/NineZero-Gun-Expansion#3]
I have the mod installed 1.19.2 and i load into a world and it is only mrCrayfish guns not the mods

**Comment by zaeonNineZero** [comment]
I'm not able to reproduce this in my 1.19.2 instance. Can you provide me with more information?

**Comment by wxjk-1** [comment]
Yes i was in 1.19.3 with the mod and then i needed to down-grade it so i took the world folder out and put it in a 1.19.2 world with more commands mod and where the tap usually is for the guns it said more commands unavalable items so i removed the more commands mod and your mod with the guns was gone

**Comment by zaeonNineZero** [comment]
That's strange. It sounds like an issue that isn't directly caused by NZGE but is affecting it and possibly preventing it from loading. But, I need to rule out some other possible causes first.

Please send me some screenshots, your mod list, and your latest.log file.

**Comment by wxjk-1** [comment]
I did some testing and i created a new world and it was working in that new world so i left and went back to that other world that i downgraded and it was working again.

**Comment by wxjk-1** [comment]
<img width="622" alt="Screenshot 2023-06-08 at 9 51 28 AM" src="https://github.com/zaeonNineZero/NineZero-Gun-Expansion/assets/96027027/05b7e4d1-1334-4215-81c1-1b86e8f412e8">

**Comment by zaeonNineZero** [comment]
Well, I'm glad the problem is resolved now. Enjoy!
