### ISSUE TITLE
[Suggestion] Adding Russian Language Pack

### ISSUE THREAD

**Issue by IBakh-Tea** [zaeonNineZero/NineZero-Gun-Expansion#4]
I have created a Russian translation for the NineZero-Gun-Expancion.
Could you include it in the official release.
Thank you in advance.

NZGE Russian pack: https://github.com/PortalRU/NineZero-Gun-Expansion_language_pack_RU/

**Comment by zaeonNineZero** [comment]
Looks good to me, I'll put out a minor update to NZGE with your translations. Thanks!

**Comment by zaeonNineZero** [comment]
All versions of NZGE have been updated with your translations. Again, thank you for your translations!

**Comment by IBakh-Tea** [comment]
Thanks a lot!
