### ISSUE TITLE
Update language files with translations for 1.3.0 content

### ISSUE THREAD

**Issue by zaeonNineZero** [zaeonNineZero/NineZero-Gun-Expansion#8]
All current language .json files have been updated with translation keys for all new items added in the upcoming 1.3.0 update.

New translations were needed for:

- Rapid SMG
- Infantry Rifle
- Automatic Sniper Rifle
- Bolt-Action Rifle
- Pump Shotgun
- Chevron Scope

Language files updated:

- [x] Simplified Chinese (zh_cn) - Partially updated by chemlzch, and finished using Google Translate
- [x] Russian (ru_ru) - Updated by PortalRU
- [x] Japanese (ja_jp) - Updated using Google Translate

Google Translate translations may need review to ensure accurate localization. Otherwise, this task is considered 'Complete.' The issue will remain open until the release of 1.3.0 in case translation corrections are needed.

Please comment on this issue if you have translation submissions or corrections. Thanks!

**Comment by chemlzh** [comment]
#9 I have update simplified Chinese translation, could you help me to merge it?

**Comment by chemlzh** [comment]
#11 The newer update of zh_cn.json. I have tried my best to translate "chevron scope" in a more native manner, but I don't know whether there's a better translation.

**Comment by IBakh-Tea** [comment]
Russian translation sucsessfuly updated

**Comment by zaeonNineZero** [comment]
I have compiled all the submitted new translations, and filled in the missing translation keys using Google Translate. Please let me know if these translations are incorrect and provide an accurate translation if necessary. Thank you chemlzh, PortalRU, and Nyattou for the translations provided!

**Comment by zaeonNineZero** [comment]
Closing this issue as v1.3.0 has been released for 1.19.2, 1.19.3, and 1.18.2. The translations will be backported to 1.16.5 as well.
